# Generated by Django 3.1.3 on 2020-11-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortedCsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('teacher', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('technical_quality', models.FloatField()),
            ],
        ),
    ]
