# Generated by Django 3.1.3 on 2020-11-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0002_sortedcsv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortedcsv',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='sortedcsv',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='sortedcsv',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='sortedcsv',
            name='technical_quality',
        ),
    ]
